services:
  - type: web
    name: inotecloud-backend
    runtime: node
    rootDir: backend
    buildCommand: echo "No frontend build needed for backend"
    startCommand: npm start
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PORT
        value: 10000 